//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DWH_entities : DbContext
    {
        public DWH_entities()
            : base("name=DWH_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_ACQ_D> T_ACQ_D { get; set; }
        public virtual DbSet<T_ACQ_M> T_ACQ_M { get; set; }
        public virtual DbSet<T_CTL_D> T_CTL_D { get; set; }
        public virtual DbSet<T_ECOMM_D> T_ECOMM_D { get; set; }
        public virtual DbSet<T_ECOMM_M> T_ECOMM_M { get; set; }
        public virtual DbSet<TEMP_ACQ_D> TEMP_ACQ_D { get; set; }
        public virtual DbSet<TEMP_CTL_D> TEMP_CTL_D { get; set; }
        public virtual DbSet<TEMP_ECOMM_D> TEMP_ECOMM_D { get; set; }
        public virtual DbSet<TEMP_ACQ> TEMP_ACQ { get; set; }
        public virtual DbSet<TEMP_ACQ_M> TEMP_ACQ_M { get; set; }
    }
}
