//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ACQ_D
    {      
        public string PAY_SYS { get; set; }
        public string ISS_TYPE { get; set; }
        public string ACQ_BANK { get; set; }
        public string TRAN_TYPE { get; set; }
        public string RC { get; set; }  
        public string MAIN_INDUSTRY { get; set; }
        public Nullable<decimal> COR_FEE { get; set; }
        public Nullable<decimal> AMT { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<decimal> CNT { get; set; }
    }
}
