//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_ACQ_D
    {
        public Nullable<System.DateTime> DATE { get; set; }
        //public string MERCHANT { get; set; }
        public Nullable<decimal> CNT { get; set; }
        public Nullable<decimal> RN { get; set; }
    }
}
