//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation_.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DWH_REPLICAEntities : DbContext
    {
        public DWH_REPLICAEntities()
            : base("name=DWH_REPLICAEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<FD_ACQ_D> FD_ACQ_D { get; set; }
        public virtual DbSet<FD_ACQ_M> FD_ACQ_M { get; set; }
        public virtual DbSet<KEY_CLIENTS> KEY_CLIENTS { get; set; }
        public virtual DbSet<parsedValues> parsedValues { get; set; }
        public virtual DbSet<REFMERCHANTS> REFMERCHANTS { get; set; }
        public virtual DbSet<SectorMasks> SectorMasks { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<T_ACQ_D> T_ACQ_D { get; set; }
        public virtual DbSet<T_ACQ_M> T_ACQ_M { get; set; }
        public virtual DbSet<T_CTL_D> T_CTL_D { get; set; }
        public virtual DbSet<T_ECOMM_D> T_ECOMM_D { get; set; }
        public virtual DbSet<T_ECOMM_M> T_ECOMM_M { get; set; }
        public virtual DbSet<table1> table1 { get; set; }
        public virtual DbSet<table2> table2 { get; set; }
        public virtual DbSet<TEMP_ACQ> TEMP_ACQ { get; set; }
        public virtual DbSet<TEMP_ACQ_D> TEMP_ACQ_D { get; set; }
        public virtual DbSet<TEMP_ACQ_M> TEMP_ACQ_M { get; set; }
        public virtual DbSet<TEMP_CTL_D> TEMP_CTL_D { get; set; }
        public virtual DbSet<TEMP_ECOMM_D> TEMP_ECOMM_D { get; set; }
    }
}
