//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation_.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_CTL_D
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string PAY_SYS { get; set; }
        public string PROC_CODE { get; set; }
        public string TR_TYPE { get; set; }
        public string MERCHANT { get; set; }
        public string TERM_ID { get; set; }
        public Nullable<decimal> RSB_TERMINAL { get; set; }
        public Nullable<decimal> LOCAL { get; set; }
        public Nullable<decimal> AMT { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<decimal> CNT { get; set; }
    }
}
